### ISSUE TITLE
UTF-8 convert

### ISSUE THREAD

**Issue by asuleymanov** [sourcegraph/jsonrpc2#15]
Greetings.
And how will your library work out if a hack with the data type html is sent?
And can anyone do something to make sure that the characters in UTF-8 format are not converted?
For example, I send `<img` src = "image.png"> the library takes this line to u003cimg src = "image.png" u003e
How can this be avoided?

**Comment by keegancsmith** [comment]
Which codec are you using? I assume the vscode codec, since that takes a `Content-Type` header. If you look at the implementation we don't actually check the content-type field. https://sourcegraph.com/github.com/sourcegraph/jsonrpc2@master/-/blob/stream.go#L136

As you can see the implementation is pretty trivial for a new codec. So if we currently don't satisfy your needs, you can just implement your own codec. https://sourcegraph.com/github.com/sourcegraph/jsonrpc2@master/-/blob/stream.go#L73:6

**Comment by asuleymanov** [comment]
Thx
